In [1]:
import ast
import numpy as np
from core.csv_db import CsvDB

In [2]:
db = CsvDB("db_data.csv", columns_names=["type_name", "schema", "description", "default_values", "default_rule_instance", "rule_type",
                         "embedding"])

the first column is the index column. e.g. - type_name


In [3]:
db.apply([{"method": "get_index", "values": ["system failure", "embedding"]}])

In [5]:
db.apply([{"method": "get_col", "values": "embedding"}])

(0,
 {'value': [array([-0.04700145,  0.00098341,  0.00694514, ...,  0.00480576,
           0.01558513, -0.01589821]),
   array([-0.04571891,  0.01389078,  0.00418912, ..., -0.01339008,
          -0.01862993, -0.01841012]),
   array([-0.04806873,  0.00784157,  0.00459556, ..., -0.02562322,
           0.0128994 , -0.02853377]),
   array([-0.03895788, -0.00989828,  0.00064138, ..., -0.00476716,
          -0.00914869, -0.02765737]),
   array([-0.04388255,  0.00507088,  0.01577844, ...,  0.00095737,
           0.01050411, -0.00212728]),
   array([-0.05597641,  0.00666464, -0.00896506, ...,  0.00791575,
          -0.00612524, -0.04012742]),
   array([-0.04455285, -0.00967128, -0.00423531, ..., -0.00345725,
          -0.0135379 , -0.03791252]),
   array([-0.04384395, -0.0231993 ,  0.00272625, ...,  0.01039576,
           0.03492595, -0.01717932]),
   array([-0.04032588,  0.00721436, -0.02595258, ..., -0.00423855,
           0.01732516, -0.04015071]),
   array([-0.02855465,  0.00396809,  0.014